### ISSUE TITLE
HW w07d05

### ISSUE THREAD

**Issue by tpeters0** [ga-dc/milk#13]
https://gist.github.com/tpeters0/b0e5aef7c98a5901d92e

**Comment by andrewsunglaekim** [comment]
`I am actually very excited about javascript` and you should be! Honestly, JS and all of it's nuances can be really difficult. And I can certainly empathize with the struggles and stress it comes with. It gets better! Once you cement this foundation you can realize(and you alluded that you've already started too see) and harness its power. Let me know if there's anything that we can do to ease the stress levels of the class. Thanks for sharing tammy!
