### ISSUE TITLE
w07d05 Javascript Reflection

### ISSUE THREAD

**Issue by SmallNic** [ga-dc/milk#14]
Javasript has been very interesting to learn. I've particularly enjoyed learning how it differs from Ruby. We can do so many of the same things, but just in different ways. We can also do so many different things with it. The idea of storing functions in variables and being able to then pass those functions in parameters is fascinating. I don't even have ideas for what to do with that just yet, but it seems very powerful. And also being able to declare global variables is actually very convenient at times. In Ruby It was difficult to have a method that altered more than one variable because we could only return one value. In javascript, I can edit the value in the function and return nothing if I don't want to.

I'm excited to continue learning javascript and the frameworks we can use with it. 

Oh and jQuery? Super interesting (and often frustrating). I'm not sure if it's best to master vanilla javscript first, to leap headfirst into jQuery or to learn them simultaneously. Thoughts?

**Comment by andrewsunglaekim** [comment]
`The idea of storing functions in variables and being able to then pass those functions in parameters is fascinating. I don't even have ideas for what to do with that just yet, but it seems very powerful.` yeah thats pretty cool. 

`I'm not sure if it's best to master vanilla javscript first, to leap headfirst into jQuery or to learn them simultaneously.` Honestly there's nothing wrong with jQuery, so many people use it. Just know what's being abstracted out and try not to be too soupy.
