### ISSUE TITLE
wk07d05:  issues

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/milk#15]
Yes they are.  

Not a good week, and not feeling so good about where I'm going to be at the end of the program.  I do like seeing what you can do with Javascript and jQuery though, and am looking forward to learning more, even if I seem to be taking longer to learn it than others....
https://gist.github.com/ae03977f420af1dc6a4d.git

**Comment by andrewsunglaekim** [comment]
Hey toby, your gist doesn't exist anymore or something, when i clicked it just send me to a blank page. Anyways, don't stress about it as much! learn as much as you can. Repetition of application is key when learning a new language/concepts. The effort you put forth is clear, I have no doubts that you will be successful in your career. The `end of the program` is whatever you want that to be. But it's just the very start of your career! You have time to really cement all of this stuff fo sho!
