### ISSUE TITLE
w07d05

### ISSUE THREAD

**Issue by britbrith4** [ga-dc/milk#17]
So last week we started JavaScript. Pretty excited that I actually understood the basic concepts. I think. When we got into jQuery I was expecting it to be much harder then it is and made it much more difficult for myself. I have a hard time even now putting myself in the mindset of a developer. I take everything very literally and I am not always sure what the computer knows. It was definitely not my best week at GA, but then again not my worst. I like when things are explained slowly and I think the best day I have had learning this JS material was when we slowly went over the in class assignment so we could understand every step. All in all I am trying to keep my head up because I am starting to get burnt out with class every day. Balancing my family life has become nearly impossible and I find myself wondering when I will actually be able to do this at the level I will need to in the future.

**Comment by jshawl** [comment]
> I like when things are explained slowly and I think the best day I have had learning this JS material was when we slowly went over the in class assignment so we could understand every step.

Definitely will incorporate more of this in the future - thanks for the feedback!

> All in all I am trying to keep my head up because I am starting to get burnt out with class every day. Balancing my family life has become nearly impossible and I find myself wondering when I will actually be able to do this at the level I will need to in the future.

Avoiding burnout is very difficult - my method is a self-enforced cut-off time for using technology, like 9pm. Have you tried any techniques to limit the amount of WDI work you do?
