### ISSUE TITLE
JavaScript Self Reflection

### ISSUE THREAD

**Issue by chadxsmith** [ga-dc/milk#18]
https://gist.github.com/chadxsmith/7e46642e39798da408cc#file-reflection_cs-js

**Comment by adambray** [comment]
Hey Chad,

Thanks for sharing this. Regarding your comment on only spending two weeks on JS, the good news is we're gonna have more time with JS. We'll have some optional lessons this week on some JS approaches, and week 10 (next week) includes backbone.js, which will really further our understanding of how to build big JS apps.

-Adam

**Comment by chadxsmith** [comment]
Hey Adam,

Thanks for the update, as well as feedback on my homework.

Since we're entering the last few weeks of WDI, and I'm participating in
UXDI's job fair on June 5th, can we briefly chat about setting priorities?
For our conversation, I'm looking for guidance on how to balance/project
time w/ preparing for UXDI's portfolio review.

Thanks
-Chad

On Sun, May 10, 2015 at 3:27 PM, Adam Bray notifications@github.com wrote:

> Closed #18 https://github.com/ga-dc/milk-and-cookies/issues/18.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/milk-and-cookies/issues/18#event-301237424.

## 

Chad Smith
UX Design + Research | UI Development |  Digital Analytics
www.chadxsmith.co
Washington, D.C.
Mobile: 240-398-4651
