### ISSUE TITLE
w07d05 hw

### ISSUE THREAD

**Issue by amaseda** [ga-dc/milk#20]
https://gist.github.com/amaseda/efdf83f427f48fcd998f

**Comment by jshawl** [comment]
> keeping code organized in Javascript has proven to be a lot harder
> than with Ruby.

Agreed! It's very difficult to organize our code without a framework - similar to how we were doing with Sinatra and our ruby command line apps.

Using a framework definitely helps - but moving forward, try grouping things that are related and thinking about how many places you'd need to change one thing or another.
