### ISSUE TITLE
w07d05 JS reflection

### ISSUE THREAD

**Issue by luminousbeam** [ga-dc/milk#25]
My experience so far with JS has been a strange one.  I had come to use it in the past, but the furthest I got, was to access some if/else and for loop stuff.  I did not apply JS to any websites, in the past, but I came across it with Codeschool and Treehouse.  At the time I was doing some prep work for the class and I stopped using it once it became a bit too complicated.  At this point, applying JS is somewhat difficult for me still.  It's always been a problem for me to apply all the concepts that I feel like I can more easily pick up.  But this was even more difficult because we just learned Ruby and the syntax and language does have a lot of similiarities.  From what I knew about JS I thought that it would be a simple front end language, but now that we are unraveling the more complex stuff that comes with it, I see it's potential and ability to be more than a fluffly type language within a similar category of html and css.  I hope to learn JS and jQuery well enough so that I can put those tools to good use and so that I can create awesome websites in the future.  I'd also like to eventually look into MEAN, which I only know a little bit about and find very intriguing.

**Comment by andrewsunglaekim** [comment]
`It's always been a problem for me to apply all the concepts that I feel like I can more easily pick up.` Yeah this is an issue that most/all developers struggle with. Fortunately for you though, we can always improve upon this with repetition of application! Thanks for sharing
