### ISSUE TITLE
more font issues (this time in sass)

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/milk#35]
I was trying to add fonts in my scss file for my github page and no matter how I write it out, it doesn't want to work. I tried making it a variable (like $font) and then using that, and in the css it comes out to the right name, but they don't use it. Google fonts with the @import do work (right now I'm using @font-face for the local fonts).

**Comment by adambray** [comment]
@lmdragun Let's look at this when we do our one-on-one if you are still having issues.
