### ISSUE TITLE
missing homework

### ISSUE THREAD

**Issue by tsetoung** [ga-dc/milk#60]
W02D01: 
https://github.com/tsetoung/wdi_dc5_tek_hw/tree/master/students/john/w02d01:d02/Poke_HW/pokearena
W05D04:
https://github.com/tsetoung/wdi_dc5_tek_hw/tree/master/students/john/w05d04/hogwarts/starter

This is the first of several more emails to follow.  Thank you.

**Comment by RobertAKARobin** [comment]
Got it. Thanks, John.
