### ISSUE TITLE
w07d05 hw: JavaScript reflection

### ISSUE THREAD

**Issue by nhashmi** [ga-dc/milk#8]
http://nabil.io/jumping-into-javascript.html

**Comment by RobertAKARobin** [comment]
Sweet blog, Nabilio! This is awesome!

I'd love to try out your Connect 4. Note that if you push things to a new branch called `gh-pages`, it'll create a Github page for it. Like this:

http://ga-dc.github.io/final-countdown/

from:

https://github.com/ga-dc/final-countdown/tree/gh-pages

**Comment by nhashmi** [comment]
Cool! I'm actually hosting my blog using my GitHub user page. I also updated the link on my post to link to the game, so now you can play [here](http://nhashmi.github.io/connect-four/). I don't have any sort of check for winning conditions yet though.
