### ISSUE TITLE
Javascript Retro

### ISSUE THREAD

**Issue by hellostella** [ga-dc/milk#9]
https://gist.github.com/hellostella/11821ea181acf1d79713

**Comment by andrewsunglaekim** [comment]
`I still find myself with this initial sense of apprehension and panic prior to starting to code something from scratch.` Man. this is a statement that truly resonates with me in particular. I felt the same way. Everyone always says, "hey just break down a bigger problem into smaller problems" While that's true, its hard to conceptualize the smaller problem or how to break down the bigger problem. And as you highlighted before, practice and repetition, whether its coding syntax, problem solving or psuedocoding, will make you a better developer. Repetition in application is key. Thanks for sharing Kevin!
